version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    container_name: subgraphrag_neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474", "-O", "/dev/null", "-q"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - rag
    restart: unless-stopped

  ner:
    build:
      context: .
      dockerfile: Dockerfile.ner
    ports:
      - "8004:8004"
    environment:
      - TRANSFORMERS_CACHE=/app/cache/transformers
      - TRANSFORMERS_OFFLINE=1
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    networks:
      - rag
    depends_on:
      - neo4j
    restart: unless-stopped

networks:
  rag:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs: 