services:
  neo4j:
    image: neo4j:4.4
    container_name: subgraphrag_neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474", "-O", "/dev/null", "-q"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - subgraphrag-net

  subgraphrag:
    build: .
    container_name: subgraphrag_api
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://subgraphrag_neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - API_KEY_SECRET=changeme
      - MODEL_BACKEND=openai
      # Uncomment and fill in your OpenAI API key if using OpenAI backend
      # - OPENAI_API_KEY=your_api_key_here
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app/data
      - app_models:/app/models
      - app_cache:/app/cache
      - app_logs:/app/logs
    restart: unless-stopped
    networks:
      - subgraphrag-net

networks:
  subgraphrag-net:
    driver: bridge

volumes:
  neo4j_data:
  app_data:
  app_models:
  app_cache:
  app_logs:
