# ... existing services ...

  ie-service:
    build:
      context: .
      dockerfile: Dockerfile.ie
    ports:
      - "8003:8003"
    environment:
      - TRANSFORMERS_CACHE=/app/cache/transformers
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  ner:
    build:
      context: .
      dockerfile: Dockerfile.ner
    ports:
      - "8004:8004"
    environment:
      - TRANSFORMERS_CACHE=/app/cache/transformers
      - TRANSFORMERS_OFFLINE=1
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    networks:
      - rag
    depends_on:
      - neo4j
    restart: unless-stopped

# ... existing services ... 